import effectPlugin from "@mpsuesser/oxlint-plugin-effect";
import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";

export default defineConfig({
  extends: [core, effectPlugin.configs.recommended],
  ignorePatterns: [
    ...core.ignorePatterns,
    "**/dist/**",
    "**/*.d.ts",
    "**/*.d.mts",
  ],
  categories: {
    correctness: "error",
    suspicious: "error",
    pedantic: "error",
    perf: "error",
  },
  rules: {
    "oxc/no-barrel-file": "off",
    "sort-keys": "off",
    "eslint/sort-keys": "off",
    "max-classes-per-file": "off",
    "eslint/max-classes-per-file": "off",
    "max-lines-per-function": "off",
    "eslint/max-lines-per-function": "off",
    "max-lines": "off",
    "eslint/max-lines": "off",
    complexity: "off",
    "eslint/complexity": "off",
    "max-depth": "off",
    "eslint/max-depth": "off",
    "func-style": "off",
    "eslint/func-style": "off",
    "no-inline-comments": "off",
    "eslint/no-inline-comments": "off",
    "jsdoc/require-param": "off",
    "jsdoc/require-returns": "off",
    "no-bitwise": "off",
    "eslint/no-bitwise": "off",
    "no-plusplus": "off",
    "eslint/no-plusplus": "off",
    "no-redeclare": "off",
    "eslint/no-redeclare": "off",
    "typescript/no-redeclare": "off",
    "typescript/no-explicit-any": "off",
    "typescript/parameter-properties": "off",
    "typescript/no-non-null-assertion": "off",
    "unicorn/numeric-separators-style": "off",
    "unicorn/no-array-callback-reference": "off",
    "unicorn/prefer-ternary": "off",
    "unicorn/prefer-array-find": "off",
    "unicorn/no-negated-condition": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-object-as-default-parameter": "off",
    "unicorn/prefer-single-call": "off",
    "unicorn/no-useless-undefined": "off",
    "eslint/prefer-destructuring": "off",
    "eslint/func-names": "off",
    "eslint/class-methods-use-this": "off",
    "eslint/no-nested-ternary": "off",
    "eslint/curly": "off",
    "promise/prefer-await-to-then": "off",
    // Effect Plugin Rules
    "effect/no-barrel-imports": "off",
    "effect/prefer-namespace-imports": "off",
    "effect/avoid-data-tagged-error": "off",
    "effect/avoid-try-catch": "off",
    "effect/avoid-direct-json": "off",
    "effect/no-unsafe-dictionary-type": "off",
    "effect/require-safety-comment-for-type-assertion": "off",
    "effect/casting-awareness": "off",
    "effect/avoid-any": "off",
    "effect/imperative-loops": "off",
    "effect/prefer-option-over-null": "off",
    "effect/use-clock-service": "off",
    "effect/no-length-comparison": "off",
    "effect/prefer-arr-match": "off",
    "effect/effect-run-in-body": "off",
    "effect/avoid-native-object-helpers": "off",
    "effect/avoid-mutable-state": "off",
    "effect/use-console-service": "off",
    "effect/avoid-process-env": "off",
    "effect/use-random-service": "off",
    "effect/avoid-platform-coupling": "off",
    "effect/avoid-node-imports": "off",
    "effect/require-schema-type-alias": "off",
    "effect/require-is-prefix-for-boolean-schema-field": "off",
    "effect/maybe-prefix-requires-option": "off",
    "effect/no-object-parameters": "off",
    "effect/yield-in-for-loop": "off",
    "effect/avoid-react-hooks": "off",
    "effect/avoid-direct-tag-checks": "off",
    "effect/no-known-value-widening": "off",
    "effect/effect-promise-vs-trypromise": "off",
    "effect/avoid-expect-in-if": "off",
    "effect/avoid-non-null-assertion": "off",
    "effect/no-unknown-parameters": "off",
    "effect/no-unknown-returns": "off",
    "effect/avoid-schema-suffix": "off",
    "effect/prefer-match-over-switch": "off",
    "effect/prefer-arr-sort": "off",
    "effect/prefer-effect-is": "off",
    "effect/no-runtime-typeof": "off",
  },
});
