import { Config, Redacted, Schema } from "effect";

import {
  cellDatabaseName,
  cellDatabaseUrl,
  defaultCellPostgresPort,
} from "./connection.ts";

/** Env keys the cell needs. `OPERON_DATABASE_URL` is derived from the other three. */
export const CELL_ENV_KEYS = [
  "OPERON_POSTGRES_PASSWORD",
  "OPERON_POSTGRES_PORT",
  "OPERON_AUTH_SECRET",
  "OPERON_DATABASE_URL",
] as const;

export type CellEnvKey = (typeof CELL_ENV_KEYS)[number];

export interface CellSecrets {
  readonly postgresPassword: Redacted.Redacted<string>;
  readonly authSecret: Redacted.Redacted<string>;
}

export interface EnsureCellEnvResult {
  readonly content: string;
  readonly added: readonly CellEnvKey[];
}

const decodePort = Schema.decodeUnknownSync(
  Schema.NumberFromString.pipe(Schema.decodeTo(Config.Port))
);

function parseEnvLines(content: string): Map<string, string> {
  const values = new Map<string, string>();
  for (const rawLine of content.split(/\r?\n/u)) {
    const line = rawLine.trim();
    if (line === "" || line.startsWith("#")) {
      continue;
    }
    const separator = line.indexOf("=");
    if (separator === -1) {
      continue;
    }
    const key = line.slice(0, separator).trim();
    const value = line.slice(separator + 1).trim();
    values.set(key, value);
  }
  return values;
}

/**
 * Appends the cell keys missing from an env file. Existing keys are never
 * rewritten, so re-running is a no-op once the file is complete. The
 * database URL is derived from the password and port that end up in the
 * file, which keeps the three values consistent.
 */
export function ensureCellEnv(
  existing: string,
  stage: string,
  secrets: CellSecrets
): EnsureCellEnvResult {
  const current = parseEnvLines(existing);
  const added: CellEnvKey[] = [];
  const lines: string[] = [];

  const configuredPassword = current.get("OPERON_POSTGRES_PASSWORD");
  const password =
    configuredPassword === undefined
      ? secrets.postgresPassword
      : Redacted.make(configuredPassword);
  if (configuredPassword === undefined) {
    lines.push(`OPERON_POSTGRES_PASSWORD=${Redacted.value(password)}`);
    added.push("OPERON_POSTGRES_PASSWORD");
  }

  const configuredPort = current.get("OPERON_POSTGRES_PORT");
  const port =
    configuredPort === undefined
      ? defaultCellPostgresPort(stage)
      : decodePort(configuredPort);
  if (configuredPort === undefined) {
    lines.push(`OPERON_POSTGRES_PORT=${port}`);
    added.push("OPERON_POSTGRES_PORT");
  }

  if (!current.has("OPERON_AUTH_SECRET")) {
    lines.push(`OPERON_AUTH_SECRET=${Redacted.value(secrets.authSecret)}`);
    added.push("OPERON_AUTH_SECRET");
  }

  if (!current.has("OPERON_DATABASE_URL")) {
    const url = cellDatabaseUrl({
      database: cellDatabaseName(stage),
      password,
      port,
    });
    lines.push(`OPERON_DATABASE_URL=${Redacted.value(url)}`);
    added.push("OPERON_DATABASE_URL");
  }

  if (lines.length === 0) {
    return { added, content: existing };
  }

  const separator = existing === "" || existing.endsWith("\n") ? "" : "\n";
  const header = `${separator}# Operon cell (stage ${stage}), generated by pnpm --dir packages/alchemy env\n`;
  return {
    added,
    content: `${existing}${header}${lines.join("\n")}\n`,
  };
}
