import type { ActionType, LinkType, ObjectType } from "@operon/schema";

/**
 * Maps an Effect Schema AST node to its TypeScript type representation.
 */
export function schemaAstToTsType(ast: any): string {
  if (!ast) return "unknown";

  switch (ast._tag) {
    case "String":
    case "StringKeyword": {
      return "string";
    }
    case "Number":
    case "NumberKeyword": {
      return "number";
    }
    case "Boolean":
    case "BooleanKeyword": {
      return "boolean";
    }
    case "Arrays": {
      return `${schemaAstToTsType(ast.rest?.[0])}[]`;
    }
    case "Literal": {
      return JSON.stringify(ast.literal);
    }
    case "Union": {
      const nonUndefined =
        ast.types?.filter((t: any) => t._tag !== "Undefined") ?? [];
      if (nonUndefined.length === 1) {
        return schemaAstToTsType(nonUndefined[0]);
      }
      if (nonUndefined.length > 0) {
        return nonUndefined.map((t: any) => schemaAstToTsType(t)).join(" | ");
      }
      return "unknown";
    }
    default: {
      return "unknown";
    }
  }
}

/**
 * Generates TypeScript client interface definitions from an ontology schema
 */
export function generateOsdkSource(schema: {
  readonly objectTypes: readonly ObjectType[];
  readonly linkTypes: readonly LinkType[];
  readonly actionTypes: readonly ActionType<any>[];
}): string {
  const lines: string[] = [
    "// AUTO-GENERATED BY @operon/osdk - DO NOT EDIT DIRECTLY",
    "import type { ObjectInstance } from '@operon/schema';",
    "import type { OperonClient, ObjectTypeAccessor, ActionAccessor } from '@operon/osdk';",
    "",
  ];

  // Generate Object Types interfaces
  for (const ot of schema.objectTypes) {
    lines.push(`export interface ${ot.id}Properties {`);
    for (const [propName, propDef] of Object.entries(ot.properties)) {
      const ast = (propDef as any).schema?.ast;
      const tsType = schemaAstToTsType(ast);
      const isRequired = propDef.required ?? false;
      lines.push(
        `  readonly ${propName}${isRequired ? "" : "?"}: ${tsType}; // ${(propDef as any).description ?? ""}`
      );
    }
    lines.push(
      "}",
      `export type ${ot.id}Instance = ObjectInstance<${ot.id}Properties>;`
    );
    lines.push("");
  }

  // Generate Typed Client Interface
  lines.push(
    "export interface TypedOperonClient extends OperonClient {",
    "  readonly objects: {"
  );
  for (const ot of schema.objectTypes) {
    lines.push(
      `    readonly ${ot.id}: ObjectTypeAccessor<${ot.id}Properties>;`
    );
  }
  lines.push("  };", "  readonly actions: {");
  for (const at of schema.actionTypes) {
    const ast = (at.parametersSchema as any)?.ast;
    let paramsType = "Record<string, unknown>";
    if (ast && (ast._tag === "Objects" || ast._tag === "TypeLiteral")) {
      const fields = (ast.propertySignatures ?? []).map((p: any) => {
        const pName = String(p.name);
        const pType = schemaAstToTsType(p.type);
        const isOpt =
          p.isOptional ||
          p.type?.context?.isOptional ||
          p.type?._tag === "Undefined" ||
          (p.type?._tag === "Union" &&
            p.type?.types?.some((t: any) => t._tag === "Undefined"));
        return `${pName}${isOpt ? "?" : ""}: ${pType}`;
      });
      paramsType = `{ ${fields.join("; ")} }`;
    }
    lines.push(`    readonly ${at.id}: ActionAccessor<${paramsType}>;`);
  }
  lines.push("  };", "}");

  return lines.join("\n");
}
